# General settings
title: Stefan Devai                                                                                                                                                                               
email: stedevai@protonmail.com
description: >
  Página de Stefan Devai sobre historia, política, programación y otros temas.
baseurl: ""
source: ""
url: "https://stefandevai.github.io"
twitter_username: SteDevai
github_username:  stefandevai

# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
 
# Menu settings
ordered_pages:
  - poesía
  - sobre

